name: Emit
options:
  deploymentTarget:
    iOS: 10.0
    macOS: 10.12
  usesTabs: false
  indentWidth: 2
targets:
  Test:
    platform: iOS
    type: bundle.unit-test
    sources:
      - test
    dependencies:
      - target: Emit_iOS
    scheme:
      testTargets:
        - Test
      gatherCoverageData: true
      environmentVariables:
        - variable: TEST
          value: YES
          isEnabled: true
  Emit:
    platform: [iOS, macOS]
    type: framework
    sources:
      - src
    settings:
      base:
        INFOPLIST_FILE: src/Info.plist
        PRODUCT_BUNDLE_IDENTIFIER: io.alexdrone.emit
        PLATFORM: platform $platform
        GCC_DEBUGGING_SYMBOLS: full,
        DEBUG_INFORMATION_FORMAT: dwarf-with-dsym
        ONLY_ACTIVE_ARCH: NO
        SWIFT_OPTIMIZATION_LEVEL: -Owholemodule
        SWIFT_VERSION: 5
      configFiles:
        Debug: configs/Debug.xcconfig
        Release: configs/Release.xcconfig
    postbuildScripts:
      - name: Dist
      - script: NAME="Emit";PRODUCT="${BUILT_PRODUCTS_DIR}";cp -R "${PRODUCT}/${NAME}.framework" ./bin;cp -R "${PRODUCT}/${NAME}.framework.dSYM" ./bin;cd ./bin;zip -r dist.zip *;
